# Generated by Django 4.0 on 2021-12-07 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('token', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='headoffice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspections.user'),
        ),
        migrations.AlterField(
            model_name='institute',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspections.user'),
        ),
        migrations.AlterField(
            model_name='spcb',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspections.user'),
        ),
    ]
