# Generated by Django 4.0 on 2021-12-08 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0002_user_alter_headoffice_user_alter_institute_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inspections.user'),
        ),
    ]
