# Generated by Django 4.0 on 2021-12-08 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0003_alter_institute_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='state',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inspections.state'),
        ),
    ]
