# Generated by Django 4.0 on 2021-12-08 11:02

from django.db import migrations, models
import inspections.models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0004_alter_institute_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field_report_images',
            name='image',
            field=models.ImageField(blank=True, default='posts/default.jpg', upload_to=inspections.models.upload_to, verbose_name='Image'),
        ),
    ]
