# Generated by Django 4.0 on 2021-12-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0005_alter_field_report_images_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='factories',
            name='status',
            field=models.IntegerField(choices=[(0, 'inspection yet to be taken'), (1, 'inspection taken from app'), (2, 'inspection report uploaded on web'), (3, 'action taken by state authorties'), (4, 'factory closed')], default=0),
        ),
    ]
