# Generated by Django 4.0 on 2021-12-08 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0010_alter_basin_name_alter_district_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='my_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_assigned', models.IntegerField(default=0)),
                ('total_inspected', models.IntegerField(default=0)),
                ('total_factory_closed', models.IntegerField(default=0)),
                ('bypass', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inspections.user')),
            ],
        ),
    ]
