# Generated by Django 4.0 on 2021-12-08 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0011_my_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='my_status',
            name='user',
        ),
        migrations.AddField(
            model_name='my_status',
            name='institute',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inspections.institute'),
        ),
        migrations.AlterField(
            model_name='institute',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspections.state'),
        ),
        migrations.AlterField(
            model_name='institute',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspections.user'),
        ),
    ]
