# Generated by Django 4.0 on 2021-12-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0013_attendance_createdon_attendance_updatedon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factories',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
