# Generated by Django 4.0 on 2021-12-21 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0016_alter_factories_region_alter_field_report_mrrname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='user', max_length=255),
        ),
    ]
