# Generated by Django 4.0 on 2021-12-22 17:34

from django.db import migrations, models
import inspections.models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0016_alter_factories_region_alter_field_report_mrrname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection_report',
            name='file',
            field=models.FileField(upload_to=inspections.models.file_upload),
        ),
    ]
