# Generated by Django 4.0 on 2021-12-21 08:04

from django.db import migrations, models
import inspections.models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0017_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspection_report',
            name='file',
        ),
        migrations.AddField(
            model_name='inspection_report',
            name='air_consent',
            field=models.FileField(blank=True, null=True, upload_to=inspections.models.file_upload),
        ),
        migrations.AddField(
            model_name='inspection_report',
            name='cgwa_noc',
            field=models.FileField(blank=True, null=True, upload_to=inspections.models.file_upload),
        ),
        migrations.AddField(
            model_name='inspection_report',
            name='consent_copy',
            field=models.FileField(blank=True, null=True, upload_to=inspections.models.file_upload),
        ),
        migrations.AddField(
            model_name='inspection_report',
            name='hazardous_consent',
            field=models.FileField(blank=True, null=True, upload_to=inspections.models.file_upload),
        ),
        migrations.AddField(
            model_name='inspection_report',
            name='inspection_report',
            field=models.FileField(blank=True, null=True, upload_to=inspections.models.file_upload),
        ),
        migrations.AddField(
            model_name='inspection_report',
            name='water_consent',
            field=models.FileField(blank=True, null=True, upload_to=inspections.models.file_upload),
        ),
    ]
