# Generated by Django 4.0 on 2021-12-21 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0018_remove_inspection_report_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inspection_report',
            old_name='cgwa_noc',
            new_name='file',
        ),
        migrations.RemoveField(
            model_name='inspection_report',
            name='air_consent',
        ),
        migrations.RemoveField(
            model_name='inspection_report',
            name='consent_copy',
        ),
        migrations.RemoveField(
            model_name='inspection_report',
            name='hazardous_consent',
        ),
        migrations.RemoveField(
            model_name='inspection_report',
            name='inspection_report',
        ),
        migrations.RemoveField(
            model_name='inspection_report',
            name='water_consent',
        ),
        migrations.AddField(
            model_name='inspection_report',
            name='file_category',
            field=models.CharField(choices=[('consent_copy', 'Consent Copy'), ('inspection_report', 'Inspection Report'), ('air_consent', 'Air Consent'), ('water_consent', 'Water Consent'), ('cgwa_noc', 'CGWA NOC'), ('hazardous_consent', 'Hazardous Consent')], default='None', max_length=100),
        ),
    ]
