# Generated by Django 4.0 on 2021-12-22 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0019_rename_cgwa_noc_inspection_report_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection_report',
            name='createdon',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='inspection_report',
            name='updatedon',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='inspection_report_data',
            name='createdon',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='inspection_report_data',
            name='updatedon',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='inspection_report_data',
            name='ZLDnorms',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='inspection_report_data',
            name='bod',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='inspection_report_data',
            name='bodLoad',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='inspection_report_data',
            name='cod',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='inspection_report_data',
            name='codLoad',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='inspection_report_data',
            name='finalRecommendation',
            field=models.TextField(),
        ),
    ]
