# Generated by Django 4.0 on 2021-12-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0020_inspection_report_createdon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection_report_data',
            name='invalidCTO',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inspection_report_data',
            name='nonInstallationofOCEMS',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inspection_report_data',
            name='otherChars',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inspection_report_data',
            name='provision',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inspection_report_data',
            name='standardExceedance',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inspection_report_data',
            name='teamNames',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inspection_report_data',
            name='temperedOCEMS',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inspection_report_data',
            name='unauthorizedDisposal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inspection_report_data',
            name='wasteWaterDischarge',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inspection_report_data',
            name='wasteWaterGeneration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inspection_report_data',
            name='ZLDnorms',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inspection_report_data',
            name='bod',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inspection_report_data',
            name='bodLoad',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inspection_report_data',
            name='cod',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inspection_report_data',
            name='codLoad',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
