# Generated by Django 4.0 on 2021-12-22 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0021_inspection_report_data_invalidcto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action_report',
            name='action',
        ),
        migrations.AddField(
            model_name='action_report',
            name='inspection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inspections.inspection'),
        ),
        migrations.AddField(
            model_name='action_report',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='action_report',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Action',
        ),
    ]
