# Generated by Django 4.0 on 2021-12-22 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0017_alter_inspection_report_file'),
        ('inspections', '0021_inspection_report_data_invalidcto_and_more'),
    ]

    operations = [
    ]
