# Generated by Django 4.0 on 2021-12-23 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0022_remove_action_report_action_action_report_inspection_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action_report_files',
            name='action_report',
        ),
        migrations.AddField(
            model_name='action_report_files',
            name='inspection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inspections.inspection'),
        ),
    ]
