# Generated by Django 4.0 on 2021-12-25 06:41

from django.db import migrations, models
import django.db.models.deletion
import inspections.models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0022_merge_20211222_2312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action_report',
            name='action',
        ),
        migrations.RemoveField(
            model_name='action_report_files',
            name='action_report',
        ),
        migrations.AddField(
            model_name='action_report',
            name='inspection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inspections.inspection'),
        ),
        migrations.AddField(
            model_name='action_report',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='action_report_files',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='action_report_files',
            name='inspection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inspections.inspection'),
        ),
        migrations.AddField(
            model_name='action_report_files',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='action_report',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='action_report',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspections.user'),
        ),
        migrations.AlterField(
            model_name='action_report',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='action_report',
            name='finalrecommendation',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='inspection_report',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=inspections.models.file_upload),
        ),
        migrations.AlterField(
            model_name='inspection_report_data',
            name='createdon',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='Action',
        ),
    ]
