# Generated by Django 4.0 on 2021-12-23 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0023_remove_action_report_files_action_report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='action_report_files',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='action_report_files',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
