# Generated by Django 4.0 on 2021-12-29 08:17

from django.db import migrations, models
import django.db.models.deletion
import inspections.models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0023_remove_action_report_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action_report_files',
            name='file',
            field=models.FileField(upload_to=inspections.models.action_file_upload),
        ),
        migrations.CreateModel(
            name='allinspection_response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inspections.action_report')),
                ('attendance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inspections.attendance')),
                ('inspection_report_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inspections.inspection_report_data')),
                ('inspections', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspections.inspection')),
            ],
        ),
    ]
