# Generated by Django 4.0 on 2021-12-23 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0024_action_report_files_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action_report',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='action_report',
            name='finalrecommendation',
            field=models.TextField(),
        ),
    ]
